definitions:
  model.UserModel:
    properties:
      email:
        type: string
      id:
        type: integer
      password:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: kangshaojun@gmail.com
    name: kangshaojun
    url: www.kangshaojun.com
  description: Gin Swagger 项目
  license: {}
  title: Gin swagger
  version: "1.0"
paths:
  /user:
    post:
      consumes:
      - application/x-json-stream
      operationId: "1"
      parameters:
      - description: 用户
        in: body
        name: article
        required: true
        schema:
          $ref: '#/definitions/model.UserModel'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.UserModel'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/model.UserModel'
      summary: 添加用户
      tags:
      - 用户
  /user/{id}:
    delete:
      consumes:
      - application/x-json-stream
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.UserModel'
      summary: 通过id删除用户
    get:
      consumes:
      - application/x-json-stream
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.UserModel'
      summary: 通过Id查询用户
swagger: "2.0"
