

GET http://localhost:8080/user/5

DELETE  http://localhost:8080/user/13

POST http://localhost:8080/user
content-type: application/json;

{
    "id":12,
    "email":"122@122.com",
    "password":"122"
}

GET http://localhost:8080/users




